package com.example.mapper;

import com.example.model.YbjAccount;
import com.example.model.YbjAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YbjAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybj_account
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    long countByExample(YbjAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybj_account
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    int deleteByExample(YbjAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybj_account
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    int deleteByPrimaryKey(Long anum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybj_account
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    int insert(YbjAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybj_account
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    int insertSelective(YbjAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybj_account
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    List<YbjAccount> selectByExample(YbjAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybj_account
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    YbjAccount selectByPrimaryKey(Long anum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybj_account
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    int updateByExampleSelective(@Param("record") YbjAccount record, @Param("example") YbjAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybj_account
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    int updateByExample(@Param("record") YbjAccount record, @Param("example") YbjAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybj_account
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    int updateByPrimaryKeySelective(YbjAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybj_account
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    int updateByPrimaryKey(YbjAccount record);
}