package com.example.model;

import java.util.Date;

public class YbjAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybj_account.anum
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    private Long anum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybj_account.aname
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    private String aname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybj_account.adate
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    private Date adate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybj_account.atype
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    private String atype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybj_account.cid
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    private Double cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybj_account.adid
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    private Integer adid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ybj_account.anum
     *
     * @return the value of ybj_account.anum
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    public Long getAnum() {
        return anum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ybj_account.anum
     *
     * @param anum the value for ybj_account.anum
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    public void setAnum(Long anum) {
        this.anum = anum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ybj_account.aname
     *
     * @return the value of ybj_account.aname
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ybj_account.aname
     *
     * @param aname the value for ybj_account.aname
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    public void setAname(String aname) {
        this.aname = aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ybj_account.adate
     *
     * @return the value of ybj_account.adate
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    public Date getAdate() {
        return adate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ybj_account.adate
     *
     * @param adate the value for ybj_account.adate
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    public void setAdate(Date adate) {
        this.adate = adate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ybj_account.atype
     *
     * @return the value of ybj_account.atype
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    public String getAtype() {
        return atype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ybj_account.atype
     *
     * @param atype the value for ybj_account.atype
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    public void setAtype(String atype) {
        this.atype = atype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ybj_account.cid
     *
     * @return the value of ybj_account.cid
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    public Double getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ybj_account.cid
     *
     * @param cid the value for ybj_account.cid
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    public void setCid(Double cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ybj_account.adid
     *
     * @return the value of ybj_account.adid
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    public Integer getAdid() {
        return adid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ybj_account.adid
     *
     * @param adid the value for ybj_account.adid
     *
     * @mbg.generated Mon Apr 15 23:11:02 EDT 2024
     */
    public void setAdid(Integer adid) {
        this.adid = adid;
    }
}