server:
  port: 8443
  servlet:
    context-path: /safe
  ssl:
    key-store-type: JKS
    key-store: classpath:keystore.jks
    key-store-password: safe123
    key-alias: safessl

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///safe
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
  type-aliases-package: team.ybj.pojo
  mapper-locations: classpath:/mappers/*.xml


jwt:
  data:
    #    jwt加密密钥
    SECRET: 7flxSYLeSerk8PMtrWlcmjxpJmZ4oSR2xrG7OB5kejc=
    #    jwt储存的请求头Authorization固定写法
    tokenHeader: Authorization
    #      jwt的过期时间(60s*60min*24h*7day)
    expiration: 604800
    #    jwt负载中拿到的头信息
    tokenHead: Bearer
